module: "end-to-end"
workdir : "."
outdir : "results/"
samplelist : "sample_list.tsv"
datadir : "fastq/"


# Flags
clusteringfast: True
genomadonly: False
viralbinning: False
prokaryotic: False
hostprok: False
