module: "end-to-end"
workdir : "."
outdir : "results/"
samplelist : "sample_list.tsv"
datadir : "fastq/"


# Flags
decontamhost: False 
clusteringfast: True
genomadonly: False
viralbinning: False
hostprok: False
