# setup working directories
workdir : "."
samplelist : "sample_list.tsv"
datadir : "fastq/"
contigdir : "results/assembly/" # should not end with a /
dbdir: "workflow/database/"


# setup database directories
vs2db: "workflow/database/vs2/"
phamerdb: "workflow/database/phabox/"

# 1) preprocessing [params]
dwnldparams : ""
pigzparams: ""
fastpparams: ""

# 2) assembly [params]
megahit_min_contig_len: 300
megahitparams: "--prune-level 3"


# 3) mapping 
bowtie2params: "--very-sensitive"

# 3) viral contig identification [params]
genomadparams: "--enable-score-calibration"
dvfparams: "--len 1500"
vs2params : "--prep-for-dramv --min-length 2500 --min-score 0 --include-groups dsDNAphage,ssDNA"
virbotparams: ""
phamerparams: "--len 2000"

genomadcutoff: 0.7
vs2cutoff: 0.7
dvfcutoff: 0.8
dvfpval: 0.05
phamercutoff: 0.9
phamerpred: "phage"


cdhitdir: "workflow/software/CD-HIT/"
cdhitparams: "-c 0.95 -d 400 -M 0 -n 5 -aS 0.85"

checkvparams: ""
