viphogshmmeval: 0.01
viphogsprop: 0.6  # Minimum proportion of annotated genes required for taxonomic assignment (default: 0.6)


phagcndb: "workflow/database/phabox"
phagcnminlen: 2000 # the minimum tested
phagcnparams: ""


diamondparams: "--query-cover 50 --subject-cover 50 --evalue 1e-5 --max-target-seqs 1000" # strongly recommend not changing this as it has been extensively tested by https://doi.org/10.1038/s41564-021-00928-6
